---
- name: Configure common Linux baseline
  hosts: all
  become: true

  roles:
    - common
    - firewall
    - fail2ban
    - docker

- name: Configure current application and observability services
  hosts: app
  become: true

  roles:
    - nginx_container
    - monitoring_stack
    - logging_stack
