---
- name: Configure common Linux baseline
  hosts: all
  become: true

  roles:
    - common
    - firewall
    - fail2ban
    - docker

- name: Configure application node
  hosts: app
  become: true

  roles:
    - app_observability_cleanup
    - nginx_container
    - multi_site_php_hosting
    - node_exporter_agent

- name: Configure observability node
  hosts: observability
  become: true

  roles:
    - observability_cleanup
    - monitoring_stack
    - logging_stack

- name: Configure application log shipper
  hosts: app
  become: true

  roles:
    - filebeat_agent
